/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "ssc-pipeline"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "ssc-pipeline"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "0.2.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * path_arg;	/**< @brief Input path for HDF5 file.  */
  char * path_orig;	/**< @brief Input path for HDF5 file original value given at command line.  */
  const char *path_help; /**< @brief Input path for HDF5 file help description.  */
  char * outpath_arg;	/**< @brief Output folder (default=`<path>/recon').  */
  char * outpath_orig;	/**< @brief Output folder (default=`<path>/recon') original value given at command line.  */
  const char *outpath_help; /**< @brief Output folder (default=`<path>/recon') help description.  */
  int block_arg;	/**< @brief Blocksize (default='10').  */
  char * block_orig;	/**< @brief Blocksize original value given at command line.  */
  const char *block_help; /**< @brief Blocksize help description.  */
  int* gpu_arg;	/**< @brief GPU device indexes.  */
  char ** gpu_orig;	/**< @brief GPU device indexes original value given at command line.  */
  unsigned int gpu_min; /**< @brief GPU device indexes's minimum occurreces */
  unsigned int gpu_max; /**< @brief GPU device indexes's maximum occurreces */
  const char *gpu_help; /**< @brief GPU device indexes help description.  */
  const char *timing_help; /**< @brief Print out timing measurements help description.  */
  const char *save_help; /**< @brief Save processed data help description.  */
  char * dataset_arg;	/**< @brief Dataset name for HDF5 file.  */
  char * dataset_orig;	/**< @brief Dataset name for HDF5 file original value given at command line.  */
  const char *dataset_help; /**< @brief Dataset name for HDF5 file help description.  */
  char * rank_arg;	/**< @brief Datatype order (ztyx or zyx).  */
  char * rank_orig;	/**< @brief Datatype order (ztyx or zyx) original value given at command line.  */
  const char *rank_help; /**< @brief Datatype order (ztyx or zyx) help description.  */
  char * order_arg;	/**< @brief Loop order ('yx' or 'zx') .  */
  char * order_orig;	/**< @brief Loop order ('yx' or 'zx')  original value given at command line.  */
  const char *order_help; /**< @brief Loop order ('yx' or 'zx')  help description.  */
  int initial_arg;	/**< @brief Initial image.  */
  char * initial_orig;	/**< @brief Initial image original value given at command line.  */
  const char *initial_help; /**< @brief Initial image help description.  */
  int final_arg;	/**< @brief Final image.  */
  char * final_orig;	/**< @brief Final image original value given at command line.  */
  const char *final_help; /**< @brief Final image help description.  */
  char * uuid_arg;	/**< @brief UUID string.  */
  char * uuid_orig;	/**< @brief UUID string original value given at command line.  */
  const char *uuid_help; /**< @brief UUID string help description.  */
  int* shape_arg;	/**< @brief Output shape for the selected axis.  */
  char ** shape_orig;	/**< @brief Output shape for the selected axis original value given at command line.  */
  unsigned int shape_min; /**< @brief Output shape for the selected axis's minimum occurreces */
  unsigned int shape_max; /**< @brief Output shape for the selected axis's maximum occurreces */
  const char *shape_help; /**< @brief Output shape for the selected axis help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int path_given ;	/**< @brief Whether path was given.  */
  unsigned int outpath_given ;	/**< @brief Whether outpath was given.  */
  unsigned int block_given ;	/**< @brief Whether block was given.  */
  unsigned int gpu_given ;	/**< @brief Whether gpu was given.  */
  unsigned int timing_given ;	/**< @brief Whether timing was given.  */
  unsigned int save_given ;	/**< @brief Whether save was given.  */
  unsigned int dataset_given ;	/**< @brief Whether dataset was given.  */
  unsigned int rank_given ;	/**< @brief Whether rank was given.  */
  unsigned int order_given ;	/**< @brief Whether order was given.  */
  unsigned int initial_given ;	/**< @brief Whether initial was given.  */
  unsigned int final_given ;	/**< @brief Whether final was given.  */
  unsigned int uuid_given ;	/**< @brief Whether uuid was given.  */
  unsigned int shape_given ;	/**< @brief Whether shape was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
